name: Jira Find issue key
description: Find an issue inside event
branding:
  icon: 'book-open'
  color: 'green'
inputs:
  string:
    description: Provide a string to extract issue key from
    required: false
  from:
    description: Find from predefined place (should be either 'branch', or 'commits')
    required: false
    default: commits
  fields:
    description: "Comma separated list of fields which should be added to outputs, example: 'summary,description'"
    required: false
    default: 'summary'
outputs:
  issue:
    description: JSON with issue data
runs:
  using: 'node16'
  main: './dist/index.js'
